#!/sbin/busybox sh

export BOOTREC_EVENT_NODE="/dev/input/event1 c 13 65"
export BOOTREC_EVENT="/dev/input/event1"
export BOOTREC_FOTA_NODE="/dev/block/mmcblk0p13 b 179 13"
export BOOTREC_FOTA="/dev/block/mmcblk0p13"
