#!/sbin/busybox sh

# Reset LEDs
busybox echo '0' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/red/brightness
busybox echo '0' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/green/brightnes
busybox echo '0' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/blue/brightness
busybox echo '0' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/button-backlight/brightness

# In animaton
b=0

for i in $(seq 0 3 255)
do
    busybox echo $i > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/red/brightness
    busybox echo $b > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/button-backlight/brightness
    b=$(($b + 1))
    
done 

for i in $(seq 0 3 255)
do
    busybox echo $i > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/green/brightness
    busybox echo $b > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/button-backlight/brightness
    b=$(($b + 1))
done

for i in $(seq 0 3 255)
do
    j=$((255 - $i))
    busybox echo $j > sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/red/brightness
    busybox echo $b > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/button-backlight/brightness
    b=$(($b + 1))
done 

# Trigger vibration
busybox echo '50' > /sys/class/timed_output/vibrator/enable

# Out animaton
for i in $(seq 0 255)
do
    j=$((255 - $i))    
    busybox echo $j > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/green/brightness
    busybox echo $j > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/button-backlight/brightness
done
